dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
  # command to install dependencies
services:
    - postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
   - psql -c "create database authors_have;" -U postgres
   - python manage.py makemigrations
   - python manage.py migrate
# command to run tests
script:
  - coverage run manage.py test
  - coverage report

after_success:
  - coveralls
